# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      cd lib
      npm install
    displayName: 'Install dependencies'

  - script: |
      cd lib
      npm run build
    displayName: 'Build library'

  - script: |
      cd lib
      echo "Add the tests here"
    displayName: 'Test library'

  - script: |
      sed -i -e 's/<TOKEN>/'$(NPM_TOKEN)'/g' ./lib/.npmrc
    displayName: '.npmrc file'

  - script: |
      sed -i -e 's/0.0.0/'0.0.0-alpha.$(Build.BuildNumber)'/g' ./lib/package.json
    displayName: 'Alpha version library'
    condition: eq(variables['Build.SourceBranchName'], 'master')

  - task: Npm@1
    inputs:
      command: 'custom' # Options: install, publish, custom
      workingDir: 'lib'
      verbose: true
      customCommand: 'publish --tag alpha'
      customRegistry: 'useNpmrc'
      publishEndpoint: 'NpmJs'
    condition: eq(variables['Build.SourceBranchName'], 'master')
    # condition: eq(variables['RELEASE_OPTION'], 'release')
